Add token to metamask button
levelkdev/dxswap-dapp pull request #381
Opened 2021-09-21 12:20 UTC by alexcherman

2021-09-21 12:58 UTC, luzzif requested changes

2021-09-21 12:58 UTC, luzzif commented on src/components/AddTokenButton/AddTokenButton.tsx
> +const MAINNET_ADDRESS = '0x6cacdb97e3fc8136805a9e7c342d866ab77d0957'
I'd import these from the SDK. It's important to have a single source of truth for these addresses.

2021-09-21 12:58 UTC, luzzif commented on src/components/AddTokenButton/AddTokenButton.tsx
> +const Button = styled.button`
I'd stylize the base button instead of the standard html button here. It has pointer cursor and removed outline, hich keep the UI consistent.

2021-09-21 13:11 UTC, Mi-Lan commented on src/components/claim/ClaimModal.tsx
> +import { AddTokenButton } from '../AddTokenButton/AddTokenButton'
One small thing I would add is that naming AddTokenButton.tsx to index.tsx since it will be just cleaner import without second AddTokenButton

2021-09-22 19:57 UTC, 0xVenky commented
I have tested the feature and it looks to be working. I will test it one more time after this is merged to develop. 👍

2021-09-23 09:35 UTC, luzzif approved these changes

2021-09-23 09:35 UTC, merged